name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - run: |
          git clone https://github.com/abdfnx/hugo-changelog-theme themes/changelog-theme
          cd themes/changelog-theme/assets
          git clone https://github.com/picturepan2/spectre
          cd ../../../
          hugo

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: "${{ secrets.PROJECTID }}"

        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
